### ISSUE TITLE
Feature Request: ADC Support

### ISSUE THREAD

**Issue by ajgowans** [MiSTer-devel/SordM5_MiSTer#1]
Would it be possible to add ADC support into the core?  I know for some cores once .cas support is added it is simply adding an additional wire to enable it.

**Comment by tdlabac** [comment]
Yes, it's possible. I'll try to get to it in a reasonable amount of time. In another project I have a choice between analog signal or CAS loading. Another option is to convert the analog signal to CAS. The necessary software is available at www.dlabi.cz

**Comment by tdlabac** [comment]
Please check. Added blind. I don't have analog input.
